version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14 # Choose your desired Node.js version

jobs:
  test:
    executor: node-executor
    steps:
      - checkout # Check out your code
      - run:
          name: Install Dependencies
          command: npm install # Or yarn install if you're using Yarn
      - run:
          name: Run Cypress Tests
          command: npx cypress run --spec "cypress/e2e/tasksTests/tasks.cy.js" # Adjust the path as necessary

workflows:
  version: 2
  test:
    jobs:
      - test
