version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.11.0-browsers # Node.js 22.11.0 with browser support

jobs:
  test:
    executor: node-executor
    steps:
      - checkout # Check out your code
      - restore_cache:
          keys:
            - cypress-cache-v1-{{ .Branch }} # Cache for Cypress binary
            - cypress-cache-v1 # Fallback cache
      - run:
          name: Install Required Libraries
          command: |
            sudo apt-get update && \
            sudo apt-get install -y \
              libnss3 \
              libxss1 \
              libasound2 \
              xvfb \
              libatk1.0-0 \
              libgtk-3-0 \
              libgdk-pixbuf2.0-0 \
              libnotify4 \
              libgbm1 \
              libxrandr2
      - run:
          name: Install Dependencies
          command: npm install # Or yarn install if you're using Yarn
      - run:
          name: Check node_modules
          command: ls -la node_modules # Verify mocha is installed
      - run:
          name: Create results directory
          command: mkdir -p cypress/results
      - run:
          name: Install Cypress
          command: npx cypress install # Ensures the Cypress binary is installed
      - run:
          name: Start Xvfb
          command: |
            Xvfb :99 -screen 0 1280x720x24 &
            echo "Xvfb started"
      - run:
          name: Run Cypress Tests
          command: |
            export DISPLAY=:99
            npx cypress run --spec "cypress/e2e/tasksTests/tasks.cy.js" --reporter mocha-junit-reporter --reporter-options "mochaFile=cypress/results/results-[hash].xml"
      - save_cache:
          paths:
            - ~/.cache/Cypress # Cache the Cypress binary
          key: cypress-cache-v1-{{ .Branch }} # Unique cache key based on branch
      - run:
          name: generate report
          command: npm run allure:report
      - store_artifacts:
          path: allure-report
          destination: CypressReport

workflows:
  version: 2
  test:
    jobs:
      - test
