version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16-browsers # Change to a confirmed available version

jobs:
  test:
    executor: node-executor
    steps:
      - checkout # Check out your code
      - run:
          name: Install Required Libraries
          command: |
            sudo apt-get update && \
            sudo apt-get install -y \
              libnss3 \
              libxss1 \
              libasound2 \
              xvfb \
              libatk1.0-0 \
              libgtk-3-0 \
              libgdk-pixbuf2.0-0 \
              libnotify4 \
              libgbm1 \
              libxrandr2 && \
            # Add Google Chrome's GPG key and repository
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - && \
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
      - run:
          name: Install Dependencies
          command: npm install # Or yarn install if you're using Yarn
      - run:
          name: Start Xvfb
          command: |
            Xvfb :99 -screen 0 1280x720x24 &
            echo "Xvfb started"
      - run:
          name: Run Cypress Tests
          command: |
            export DISPLAY=:99
            npx cypress run --spec "cypress/e2e/tasksTests/tasks.cy.js" # Adjust the path as necessary

workflows:
  version: 2
  test:
    jobs:
      - test
