version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14-browsers # Choose your desired Node.js version
      - image: circleci/python:3.8 # Additional Docker image for libraries (optional)

jobs:
  test:
    executor: node-executor
    steps:
      - checkout # Check out your code
      - run:
          name: Clean APT Cache and Install Libraries
          command: |
            sudo apt-get clean && \
            sudo apt-get update && \
            sudo apt-get install -y libnss3 libxss1 libasound2
      - run:
          name: Install Dependencies
          command: npm install # Or yarn install if you're using Yarn
      - run:
          name: Run Cypress Tests
          command: npx cypress run --spec "~/AquaProjects/FinalProject/cypress/e2e/tasksTests/tasks.cy.js" # Adjust the path as necessary

workflows:
  version: 2
  test:
    jobs:
      - test
